apiVersion: v1
kind: Service
metadata:
  labels:
    app: deployment-frontend
  name: service-frontend
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: deployment-frontend
  type: NodePort