name: Abdullahi

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x

    - name: Build and test
      run: |
        cd frontend
        go test -v ./...
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ls -l frontend/
    - name: Build and push Docker images
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: jakub210/myfirstapp:latest
        registry: docker.io
        docker_username: ${{ secrets.USERNAME }}
        docker_password: ${{ secrets.PASSWORD }}
