name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > kubeconfig

      - name: Set execute permission
        run: chmod +x deploy.sh

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ./kubeconfig
        run: ./deploy.sh
