name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > kubeconfig-base64
        env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG }}

      - name: Set execute permission
        run: chmod +x deploy.sh

      - name: Deploy to Kubernetes
        run: ../../kubernetes_yaml/deploy.sh
