apiVersion: v1
kind: Config
clusters:
- name: my-cluster
  cluster:
    server: API_SERVER_URL
    certificate-authority-data: BASE64_CERT_AUTH_DATA
contexts:
- name: my-context
  context:
    cluster: my-cluster
    user: my-user
users:
- name: my-user
  user:
    # Add authentication details here
current-context: my-context
