name: Run Tests, Build Docker Images, and Deploy to Kubernetes

on:
  push:
    branches:
      - main
      - Bouzan

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x

    - name: Build and test
      run: |
        cd frontend
        go test -v ./...
        
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: frontend/test_report.txt

  docker:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build frontend Docker image
      run: |
        cd frontend
        docker build -t ghcr.io/${{ github.repository_owner }}/group04b-frontend:latest .

    - name: Build backend Docker image
      run: |
        cd backend
        docker build -t ghcr.io/${{ github.repository_owner }}/group04b-backend:latest .

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push frontend Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/group04b-frontend:latest

    - name: Push backend Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/group04b-backend:latest

  deploy:
    if: github.ref == 'refs/heads/Bouzan'
    needs: docker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubernetes context
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Deploy frontend to Kubernetes
      uses: azure/k8s-deploy@v1
      with:
       manifests: ./path-to-manifests/frontend-deployment.yaml
       namespace: default
       action: deploy
       strategy: none
       traffic-split-method: pod
       baseline-and-canary-replicas: 0
       percentage: 0
       force: false
      env:
       KUBECONFIG: /home/runner/work/_temp/kubeconfig_1692627402756

    - name: Deploy backend to Kubernetes
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          ./path-to-manifests/backend-deployment.yaml
        namespace: default
        action: 'apply'
